using OrdinaryDiffEq
include(joinpath("..", "auxiliary_functions.jl"))

output_directory = joinpath(OUT_DIR, "airfoil", "NACA_6412")

geometry_name = "NACA_6412.asc"
file = joinpath(DATA_DIR, "airfoil", geometry_name)

d_airfoil = 0.13895
factor = 400
particle_spacing = 1 / factor

tlsph = true

boundary_thickness = 10 * particle_spacing

maxiters = factor == 25 ? 10000 : 4000

smoothing_kernel = SchoenbergQuinticSplineKernel{2}()

h_factor = factor == 25 ? 0.75 : 0.8
smoothing_length = h_factor * particle_spacing

background_pressure = 1
density = 1.0

# ==========================================================================================
# ==== Setup 1 (Airfoil)
geometry = load_geometry(file)

signed_distance_field = SignedDistanceField(geometry, particle_spacing;
                                            use_for_boundary_packing=true,
                                            max_signed_distance=boundary_thickness)

point_in_geometry_algorithm = WindingNumberJacobson(; geometry,
                                                    winding_number_factor=sqrt(eps()),
                                                    hierarchical_winding=true)

if factor == 25
    # For very low resolution, additional sampling points are generated by using a smaller particle spacing during the initial sampling.
    # This is possible because the mass of the particles is calculated using the volume of the geometry.
    shape_sampled_ = ComplexShape(geometry; particle_spacing=0.85 * particle_spacing,
                                  density,
                                  point_in_geometry_algorithm)
    shape_sampled = InitialCondition(; coordinates=shape_sampled_.coordinates,
                                     density=density,
                                     particle_spacing=particle_spacing)

    trixi2vtk(ComplexShape(geometry; particle_spacing, density,
                           point_in_geometry_algorithm),
              prefix="lattice_dp_$(factor)$(tlsph ? "_tlsph" : "")",
              output_directory=output_directory)
else
    shape_sampled = ComplexShape(geometry; particle_spacing, density,
                                 point_in_geometry_algorithm)

    trixi2vtk(shape_sampled, prefix="lattice_dp_$(factor)$(tlsph ? "_tlsph" : "")",
              output_directory=output_directory)
end

shape_sampled.mass .= density * TrixiParticles.volume(geometry) /
                      nparticles(shape_sampled)

boundary_sampled = sample_boundary(signed_distance_field; boundary_density=density,
                                   boundary_thickness, place_on_shell=tlsph)

trixi2vtk(boundary_sampled, prefix="lattice_boundary_dp_$(factor)$(tlsph ? "_tlsph" : "")",
          output_directory=output_directory)

packing_system = ParticlePackingSystem(shape_sampled;
                                       smoothing_kernel=smoothing_kernel,
                                       smoothing_length=smoothing_length,
                                       smoothing_length_interpolation=smoothing_length,
                                       signed_distance_field, place_on_shell=tlsph,
                                       background_pressure)

boundary_system = ParticlePackingSystem(boundary_sampled;
                                        smoothing_kernel=smoothing_kernel,
                                        smoothing_length=smoothing_length,
                                        smoothing_length_interpolation=smoothing_length,
                                        boundary_compress_factor=0.9,
                                        is_boundary=true, signed_distance_field,
                                        place_on_shell=tlsph, background_pressure)

# ==========================================================================================
# ==== Packing 1 (Airfoil)
semi = Semidiscretization(packing_system, boundary_system)

tspan = (0, factor * 1000.0)
ode = semidiscretize(semi, tspan)

info_callback = InfoCallback(interval=200)

callbacks = CallbackSet(UpdateCallback(), info_callback)

sol = solve(ode, RDPK3SpFSAL35();
            abstol=1e-6, # Default abstol is 1e-6 (may need to be tuned to prevent boundary penetration)
            reltol=1e-4, # Default reltol is 1e-3 (may need to be tuned to prevent boundary penetration)
            save_everystep=false, maxiters=maxiters, callback=callbacks)

packed_ic = InitialCondition(sol, packing_system, semi)
packed_boundary_ic = InitialCondition(sol, boundary_system, semi)

trixi2vtk(packed_ic, prefix="packed_dp_$(factor)$(tlsph ? "_tlsph" : "")",
          output_directory=output_directory)
trixi2vtk(packed_boundary_ic, prefix="packed_boundary_dp_$(factor)$(tlsph ? "_tlsph" : "")",
          output_directory=output_directory)

# ==========================================================================================
# ==== Setup 2 (Fluid domain)
tank_domain = RectangularTank(particle_spacing, (4.0, 8 * d_airfoil), (4.0, 8 * d_airfoil),
                              min_coordinates=(-1, -4 * d_airfoil), density)

sampled_outer_domain = setdiff(tank_domain.fluid, packed_ic)

trixi2vtk(sampled_outer_domain, prefix="lattice_domain_dp_$factor",
          output_directory=output_directory)

pack_window = TrixiParticles.Polygon(stack([
                                               [-0.5, -2 * d_airfoil],
                                               [1.5, -2 * d_airfoil],
                                               [1.5, 2 * d_airfoil],
                                               [-0.5, 2 * d_airfoil],
                                               [-0.5, -2 * d_airfoil]
                                           ]))

pack_domain = intersect(sampled_outer_domain, pack_window)
fixed_domain = setdiff(sampled_outer_domain, pack_window)

fixed_system_1 = ParticlePackingSystem(fixed_domain;
                                       smoothing_kernel=smoothing_kernel,
                                       smoothing_length=smoothing_length,
                                       signed_distance_field=nothing,
                                       background_pressure, fixed_system=true)

fixed_system_2 = ParticlePackingSystem(packed_ic;
                                       smoothing_kernel=smoothing_kernel,
                                       smoothing_length=smoothing_length,
                                       signed_distance_field=nothing,
                                       background_pressure, fixed_system=true)

packing_system = ParticlePackingSystem(pack_domain;
                                       smoothing_kernel=smoothing_kernel,
                                       smoothing_length=smoothing_length,
                                       signed_distance_field=nothing,
                                       background_pressure)

# ==========================================================================================
# ==== Simulation 2
semi = Semidiscretization(packing_system, fixed_system_1, fixed_system_2)

tspan = (0, 10000.0)
ode = semidiscretize(semi, tspan)

info_callback = InfoCallback(interval=200)
callbacks = CallbackSet(UpdateCallback(), info_callback)

time_integrator = RDPK3SpFSAL35()

sol_1 = solve(ode, time_integrator; abstol=1e-7, reltol=1e-4,
              save_everystep=false, maxiters=1000, callback=callbacks)

packed_fluid_domain = union(InitialCondition(sol_1, packing_system, semi), fixed_domain)

trixi2vtk(packed_fluid_domain, prefix="packed_domain_dp_$factor",
          output_directory=output_directory)
